#!/usr/bin/env python3
"""Regenerate Iris Drive app icons from one vector source."""
from __future__ import annotations

import math
import shutil
import subprocess
import sys
import tempfile
from functools import lru_cache
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
SVG_SOURCE = REPO / "linux/resources/iris-drive.svg"

BG = (0, 0, 0, 255)
VIEWBOX = 512
CENTER = VIEWBOX / 2

# Original iris-drive geometry, scaled to match the visual footprint of the
# iris-native / iris-chat icon family once rasterized into app-icon canvases.
FOREGROUND_SCALE = 1.075
CIRCLE_RADIUS = 150
DOT_RADIUS = 36
STROKE_WIDTH = 52
READER_START = (104, 408)
READER_END = (196, 316)

SWEEP_SEGMENTS = 720
SWEEP_SEGMENT_OVERLAP_DEGREES = 0.2
SWEEP_COLORS = [
    "#F43F5E",
    "#F97316",
    "#FACC15",
    "#22C55E",
    "#06B6D4",
    "#3B82F6",
    "#8B5CF6",
    "#F43F5E",
]

MAC_DIR = REPO / "macos/Resources/Assets.xcassets/AppIcon.appiconset"
LINUX_RES_DIR = REPO / "linux/resources"
WINDOWS_RES_DIR = REPO / "windows"

MAC_OUTPUTS = {
    "icon_16x16.png": 16,
    "icon_16x16@2x.png": 32,
    "icon_32x32.png": 32,
    "icon_32x32@2x.png": 64,
    "icon_128x128.png": 128,
    "icon_128x128@2x.png": 256,
    "icon_256x256.png": 256,
    "icon_256x256@2x.png": 512,
    "icon_512x512.png": 512,
    "icon_512x512@2x.png": 1024,
}

LINUX_OUTPUTS = {
    "iris-drive-16.png": 16,
    "iris-drive-22.png": 22,
    "iris-drive-24.png": 24,
    "iris-drive-32.png": 32,
    "iris-drive-48.png": 48,
    "iris-drive-64.png": 64,
    "iris-drive-128.png": 128,
    "iris-drive-256.png": 256,
    "iris-drive-512.png": 512,
}

WINDOWS_ICO_SIZES = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]


def hex_to_rgb(color: str) -> tuple[int, int, int]:
    color = color.removeprefix("#")
    return int(color[0:2], 16), int(color[2:4], 16), int(color[4:6], 16)


def interpolate_color(angle_degrees: float) -> str:
    angle = angle_degrees % 360
    position = angle / 360 * (len(SWEEP_COLORS) - 1)
    index = math.floor(position)
    fraction = position - index
    c1 = hex_to_rgb(SWEEP_COLORS[index])
    c2 = hex_to_rgb(SWEEP_COLORS[min(index + 1, len(SWEEP_COLORS) - 1)])
    channels = [
        round(c1[channel] + (c2[channel] - c1[channel]) * fraction)
        for channel in range(3)
    ]
    return f"#{channels[0]:02X}{channels[1]:02X}{channels[2]:02X}"


def point(angle_degrees: float, radius: float) -> tuple[float, float]:
    radians = math.radians(angle_degrees)
    return (
        CENTER + math.cos(radians) * radius,
        CENTER + math.sin(radians) * radius,
    )


def svg_sector_path(start_degrees: float, end_degrees: float) -> str:
    radius = VIEWBOX
    x0, y0 = point(start_degrees, radius)
    x1, y1 = point(end_degrees, radius)
    return (
        f"M {CENTER:.3f} {CENTER:.3f} "
        f"L {x0:.3f} {y0:.3f} "
        f"A {radius:.3f} {radius:.3f} 0 0 1 {x1:.3f} {y1:.3f} Z"
    )


def svg_source() -> str:
    sectors = []
    for index in range(SWEEP_SEGMENTS):
        start = index * 360 / SWEEP_SEGMENTS
        end = (index + 1) * 360 / SWEEP_SEGMENTS
        color = interpolate_color((start + end) / 2)
        path = svg_sector_path(
            start - SWEEP_SEGMENT_OVERLAP_DEGREES,
            end + SWEEP_SEGMENT_OVERLAP_DEGREES,
        )
        sectors.append(f'    <path d="{path}" fill="{color}"/>')

    sector_markup = "\n".join(sectors)
    sx, sy = READER_START
    ex, ey = READER_END
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 {VIEWBOX} {VIEWBOX}" role="img" aria-label="Iris Drive">
  <!-- Generated by scripts/regen_app_icons.py. -->
  <defs>
    <mask id="iris-drive-mask" maskUnits="userSpaceOnUse" x="0" y="0" width="{VIEWBOX}" height="{VIEWBOX}">
      <rect width="{VIEWBOX}" height="{VIEWBOX}" fill="#000000"/>
      <g transform="translate({CENTER:.3f} {CENTER:.3f}) scale({FOREGROUND_SCALE:.3f}) translate({-CENTER:.3f} {-CENTER:.3f})">
        <circle cx="{CENTER:.3f}" cy="{CENTER:.3f}" r="{CIRCLE_RADIUS:.3f}" fill="none" stroke="#ffffff" stroke-width="{STROKE_WIDTH:.3f}"/>
        <circle cx="{CENTER:.3f}" cy="{CENTER:.3f}" r="{DOT_RADIUS:.3f}" fill="#ffffff"/>
        <path d="M {sx:.3f} {sy:.3f} L {ex:.3f} {ey:.3f}" fill="none" stroke="#ffffff" stroke-width="{STROKE_WIDTH:.3f}" stroke-linecap="round"/>
      </g>
    </mask>
  </defs>
  <rect width="{VIEWBOX}" height="{VIEWBOX}" fill="#000000"/>
  <g mask="url(#iris-drive-mask)">
{sector_markup}
  </g>
</svg>
"""


def write_svg_source() -> None:
    SVG_SOURCE.parent.mkdir(parents=True, exist_ok=True)
    SVG_SOURCE.write_text(svg_source(), encoding="utf-8")
    print(f"SVG source: {SVG_SOURCE.relative_to(REPO)}")


def rasterize_icon(size: int) -> Image.Image:
    resvg = shutil.which("resvg")
    rsvg_convert = shutil.which("rsvg-convert")
    if not resvg and not rsvg_convert:
        print("resvg or rsvg-convert is required to regenerate icons.", file=sys.stderr)
        sys.exit(1)

    with tempfile.NamedTemporaryFile(suffix=".png") as tmp:
        if resvg:
            subprocess.run(
                [
                    resvg,
                    "--width",
                    str(size),
                    "--height",
                    str(size),
                    str(SVG_SOURCE),
                    tmp.name,
                ],
                check=True,
            )
        else:
            subprocess.run(
                [
                    rsvg_convert,
                    "-f",
                    "png",
                    "-w",
                    str(size),
                    "-h",
                    str(size),
                    "-o",
                    tmp.name,
                    str(SVG_SOURCE),
                ],
                check=True,
            )
        return Image.open(tmp.name).convert("RGBA")


@lru_cache(maxsize=None)
def render_icon(size: int, rgb: bool = False) -> Image.Image:
    icon = rasterize_icon(size)
    return icon.convert("RGB") if rgb else icon


def write_outputs(out_dir: Path, outputs: dict[str, int], rgb: bool) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for filename, size in outputs.items():
        path = out_dir / filename
        img = render_icon(size, rgb=rgb)
        img.save(path, "PNG", optimize=True)
        print(f"  {path.relative_to(REPO)} ({size}x{size})")


def write_icns() -> None:
    iconutil = shutil.which("iconutil")
    if not iconutil:
        print("  iconutil not found; skipping macOS .icns")
        return

    pairs = [
        (16, "icon_16x16.png"),
        (32, "icon_16x16@2x.png"),
        (32, "icon_32x32.png"),
        (64, "icon_32x32@2x.png"),
        (128, "icon_128x128.png"),
        (256, "icon_128x128@2x.png"),
        (256, "icon_256x256.png"),
        (512, "icon_256x256@2x.png"),
        (512, "icon_512x512.png"),
        (1024, "icon_512x512@2x.png"),
    ]

    with tempfile.TemporaryDirectory(dir=MAC_DIR) as tmp:
        iconset_dir = Path(tmp) / "app_icon.iconset"
        iconset_dir.mkdir()
        for size, name in pairs:
            img = render_icon(size, rgb=True)
            img.save(iconset_dir / name, "PNG", optimize=True)

        out = MAC_DIR / "app_icon.icns"
        subprocess.run(
            [iconutil, "-c", "icns", "-o", str(out), str(iconset_dir)],
            check=True,
        )
    print(f"  {out.relative_to(REPO)}")


def write_windows_ico() -> None:
    frames = [render_icon(size[0]) for size in WINDOWS_ICO_SIZES]
    out = WINDOWS_RES_DIR / "IrisDrive.ico"
    frames[-1].save(
        out,
        format="ICO",
        sizes=WINDOWS_ICO_SIZES,
        append_images=frames[:-1],
    )
    print(f"  {out.relative_to(REPO)}")


def main() -> None:
    write_svg_source()
    print("macOS:")
    write_outputs(MAC_DIR, MAC_OUTPUTS, rgb=True)
    write_icns()
    print("Linux:")
    write_outputs(LINUX_RES_DIR, LINUX_OUTPUTS, rgb=False)
    print("Windows:")
    write_windows_ico()


if __name__ == "__main__":
    main()
